[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "git lfs pull"
buildArgs = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[deploy]
startCommand = "uvicorn quran_model.serve_quran_model:app --host 0.0.0.0 --port 8001"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 