[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "git lfs pull"

[deploy]
startCommand = "python -m uvicorn quran_model.serve_quran_model:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[mount]
source = "/app/quran_model"
destination = "/app/quran_model" 